config/routes.rb
TraderPog::Application.routes.draw do

  resources :users do
    collection do
      get 'facebook'
    end

    member do
      put 'updatemember'
    end

    resources :sales
    resources :user_leaderboards
    resources :userconfigs
    resources :user_flyers do
      resources :flyer_paths do
        collection do
          put 'setdone'
        end
      end
    end
  end

  resources :flyer_infos do
    resources :flyer_locs
  end

  resources :posts do
    collection do
      get 'scan'
    end

    collection do
      get 'beacons'
    end

    resources :post_items
  end

  resources :item_infos do
    collection do
      get 'tier'
    end

    resources :item_locs
  end

  match 'gameinfo' => 'GameInfo#show', :via => [:get]











end

app/models/item_info.rb
class ItemInfo < ActiveRecord::Base
  validates :tier, :presence => true
  validates :price, :presence => true
  validates :supplymax, :presence => true
  validates :supplyrate, :presence => true
  validates :multiplier, :presence => true

  has_many :item_locs, :dependent => :destroy
end

app/controllers/item_infos_controller.rb
require 'logging'

class ItemInfosController < ApplicationController

  include Logging

  # @param [Object] index
  def getitem(index)
    # Get the Accept-Language first. If it doesn't exist, default to en
    @language = ApplicationHelper.preferred_language(request.headers["Accept-Language"])
    @item_info = ItemInfo.find(index, :select => "id, img, price, supplymax, supplyrate, multiplier, tier, disabled")
    @item_loc = ItemInfosHelper.getitemloc(@item_info, @language)
    @item_info.as_json.merge(@item_loc.first.as_json)
  end

  # GET /item_infos
  # GET /item_infos.json
  def index
    @item_infos = ItemInfo.all(:select => "id, img, price, supplymax, supplyrate, multiplier, tier, disabled")
    @language = ApplicationHelper.preferred_language(request.headers["Accept-Language"])

    @complete_items = @item_infos.collect { |item_info|
      item_info.as_json.merge(ItemInfosHelper.getitemloc(item_info, @language).first.as_json)
    }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @complete_items }
    end
  end

  # GET /item_infos/1
  # GET /item_infos/1.json
  def show
    respond_to do |format|
      format.html { # show.html.erb
        @item_info = ItemInfo.find(params[:id])
      }
      format.json {
        render json: getitem(params[:id])
      }
    end
  end

  # GET /item_infos/new
  # GET /item_infos/new.json
  def new
    respond_to do |format|
      format.html {  # new.html.erb
        @item_info = ItemInfo.new
      }
    end
  end

  # GET /item_infos/1/edit
  def edit
    @item_info = ItemInfo.find(params[:id])
  end

  # POST /item_infos
  # POST /item_infos.json
  def create
    respond_to do |format|
      format.html {
        @item_info = ItemInfo.new(params[:item_info])
        if @item_info.save
          GameInfoHelper.updateTime
          redirect_to @item_info, notice: 'Item info was successfully created.'
        else
          render action: "new"
        end
      }
      format.json {
        if ApplicationHelper.validate_key(request.headers["Validation-Key"])
          @item_info = ItemInfo.new(params[:item_info])
          if @item_info.save
            GameInfoHelper.updateTime
            render json: @item_info.as_json(:only => [:id])
          else
            create_error(:unprocessable_entity, :post, params[:item_info], @item_info.errors)
          end
        else
          create_error(:forbidden, :post, params[:item_info], "Data incorrect")
        end
      }
    end
  end

  # PUT /item_infos/1
  # PUT /item_infos/1.json
  def update
    # JSON is not allowed to modify item_infos. Must be done through the website.
    respond_to do |format|
      format.html {
        @item_info = ItemInfo.find(params[:id])
        if @item_info.update_attributes(params[:item_info])
          GameInfoHelper.updateTime
          redirect_to @item_info, notice: 'Item info was successfully updated.'
        else
          render action: "edit"
        end
      }
      format.json {
        create_error(:forbidden, :put, params[:item_info], "Data incorrect")
      }
    end
  end

  # DELETE /item_infos/1
  # DELETE /item_infos/1.json
  def destroy
    # JSON is not allowed to destroy item_infos. Must be done through the website.
    respond_to do |format|
      format.html {
        @item_info = ItemInfo.find(params[:id])
        @item_info.destroy
        GameInfoHelper.updateTime
        redirect_to item_infos_url
      }
      format.json {
        create_error(:forbidden, :put, params[:item_info], "Data incorrect")
      }
    end
  end

  # GET /item_infos/tier
  def tier
    @tier = request.headers["Item-Tier"]
    @item_infos = ItemInfo.where("tier = ?", Integer(@tier)).select("id, img, price, supplymax, supplyrate, multiplier, tier, disabled")
    @language = ApplicationHelper.preferred_language(request.headers["Accept-Language"])

    @tiered_items = @item_infos.collect { |item_info|
      item_info.as_json.merge(ItemInfosHelper.getitemloc(item_info, @language).first.as_json)
    }

    respond_to do |format|
      format.json {
        render json: @tiered_items.as_json
      }
    end
  end
end

app/helpers/item_infos_helper.rb
module ItemInfosHelper
  ##
  # Returns a hash containing for the item at itemid, including localized info
  ##
  # @param [integer] itemid
  def ItemInfosHelper.getitem(itemid)
    item_info = ItemInfo.find(itemid, :select => "id, price, supplymax, supplyrate, multiplier")
    item_locs = ItemLoc.where("item_info_id = ?",
                              item_info.id).select("id, item_info_id, locale, localized_name, localized_desc")
    item_info = item_info.as_json
    item_info['locale_info'] = item_locs.as_json
    return item_info
  end

  ##
  # Returns a hash containing for the item at itemid with locale specific info flattened
  # into the structure
  ##
  # @param [integer] itemid
  # @param [string] locale
  def ItemInfosHelper.getitembylocale(itemid, locale)

    item_info = ItemInfosHelper.getitem(itemid)
    locale_info = item_info['locale_info'].select {
                    |loc| (loc['locale'].casecmp locale) == 0
                  }
    item_info.except!('locale_info').merge!(locale_info.first.as_json.except!('id', 'item_info_id'))
    return item_info
  end

  def ItemInfosHelper.getitemloc(item_info, language)
    item_loc_array = item_info.item_locs.where("locale = ?", language).select("locale, localized_name, localized_desc")
    if item_loc_array.empty?
      # There is no corresponding item_loc for this item_info. Fake one for now to prevent failure.
      item_loc = ItemLoc.new
      item_loc_array = [ item_loc ]
    end
    item_loc_array
  end

end


app/views/item_infos/_form.html.erb
<%= form_for(@item_info) do |f| %>
  <% if @item_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_info.errors.count, "error") %> prohibited this item_info from being saved:</h2>

      <ul>
      <% @item_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tier %><br />
    <%= f.number_field :tier %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :supplymax %><br />
    <%= f.number_field :supplymax %>
  </div>
  <div class="field">
    <%= f.label :supplyrate %><br />
    <%= f.number_field :supplyrate %>
  </div>
  <div class="field">
    <%= f.label :multiplier %><br />
    <%= f.number_field :multiplier %>
  </div>
  <div class="field">
    <%= f.label :img %><br />
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :disabled %><br />
    <%= f.check_box :disabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_infos/edit.html.erb
<h1>Editing item_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_info %> |
<%= link_to 'Back', item_infos_path %>

app/views/item_infos/index.html.erb
<h1>Listing item_infos</h1>

<table>
  <tr>
    <th>Tier</th>
    <th>Price</th>
    <th>SupplyMax</th>
    <th>SupplyRate</th>
    <th>Multiplier</th>
    <th>Image</th>
    <th>Disabled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @item_infos.each do |item_info| %>
  <tr>
    <td><%= item_info.tier %></td>
    <td><%= item_info.price %></td>
    <td><%= item_info.supplymax %></td>
    <td><%= item_info.supplyrate %></td>
    <td><%= item_info.multiplier %></td>
    <td><%= item_info.img %></td>
    <td><%= item_info.disabled %></td>
    <td><%= link_to 'Show', item_info %></td>
    <td><%= link_to 'Edit', edit_item_info_path(item_info) %></td>
    <td><%= link_to 'Destroy', item_info, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item info', new_item_info_path %>

app/views/item_infos/new.html.erb
<h1>New item_info</h1>

<%= render 'form' %>

<%= link_to 'Back', item_infos_path %>

app/views/item_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tier:</b>
  <%= @item_info.tier %>
</p>

<p>
  <b>Price:</b>
  <%= @item_info.price %>
</p>

<p>
  <b>SupplyMax:</b>
  <%= @item_info.supplymax %>
</p>

<p>
  <b>SupplyRate:</b>
  <%= @item_info.supplyrate %>
</p>

<p>
  <b>Multiplier:</b>
  <%= @item_info.multiplier %>
</p>

<p>
  <b>Image:</b>
  <%= @item_info.img %>
</p>

<p>
  <b>Disabled:</b>
  <%= @item_info.disabled %>
</p>

<h2>Localized information</h2>
<% @item_info.item_locs.each do |item_loc| %>
    <p>
      <b>Locale:</b>
      <%= item_loc.locale %>
    </p>

    <p>
      <b>Localized name:</b>
      <%= item_loc.localized_name %>
    </p>

    <p>
      <b>Localized description:</b>
      <%= item_loc.localized_desc %>
    </p>
<% end %>

<h2>Add localized information:</h2>
<%= form_for([@item_info, @item_info.item_locs.build]) do |f| %>
    <div class="field">
      <%= f.label :locale %><br />
      <%= f.text_field :locale %>
    </div>
    <div class="field">
      <%= f.label :localized_name %><br />
      <%= f.text_field :localized_name %>
    </div>
    <div class="field">
      <%= f.label :localized_desc %><br />
      <%= f.text_field :localized_desc %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Edit', edit_item_info_path(@item_info) %> |
<%= link_to 'Back', item_infos_path %>