config/routes.rb
TraderPog::Application.routes.draw do

  resources :users do
    collection do
      get 'facebook'
    end

    member do
      put 'updatemember'
    end

    resources :sales
    resources :user_leaderboards
    resources :userconfigs
    resources :user_flyers do
      resources :flyer_paths do
        collection do
          put 'setdone'
        end
      end
    end
  end

  resources :flyer_infos do
    resources :flyer_locs
  end

  resources :posts do
    collection do
      get 'scan'
    end

    collection do
      get 'beacons'
    end

    resources :post_items
  end

  resources :item_infos do
    collection do
      get 'tier'
    end

    resources :item_locs
  end

  match 'gameinfo' => 'GameInfo#show', :via => [:get]











end

app/models/flyer_info.rb
class FlyerInfo < ActiveRecord::Base
  has_many :flyer_locs, :dependent => :destroy

  validates :capacity, :presence => true
  validates :speed, :presence => true
  validates :stormresist, :presence => true
  validates :multiplier, :presence => true
  validates :price, :presence => true
  validates :tier, :presence => true
  validates :load_time, :presence => true
end

app/controllers/flyer_infos_controller.rb
require 'logging'

class FlyerInfosController < ApplicationController

  include Logging

  # @param [Object] index
  def getflyer(index)
    # Get the Accept-Language first. If it doesn't exist, default to en
    @language = ApplicationHelper.preferred_language(request.headers["Accept-Language"])
    @flyer_info = FlyerInfo.find(index, :select => "id, topimg, sideimg, capacity, speed, stormresist, multiplier, price, tier, load_time, disabled")
    @flyer_loc = FlyerInfosHelper.getflyerloc(@flyer_info, @language)
    @flyer_info.as_json.merge(@flyer_loc.first.as_json)
  end

  # GET /flyer_infos
  # GET /flyer_infos.json
  def index
    @flyer_infos = FlyerInfo.all(:select => "id, topimg, sideimg, capacity, speed, stormresist, multiplier, price, tier, load_time, disabled")
    @language = ApplicationHelper.preferred_language(request.headers["Accept-Language"])

    @complete_flyers = @flyer_infos.collect { |flyer_info|
      flyer_info.as_json.merge(FlyerInfosHelper.getflyerloc(flyer_info, @language).first.as_json)
    }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @complete_flyers }
    end
  end

  # GET /flyer_infos/1
  # GET /flyer_infos/1.json
  def show

    respond_to do |format|
      format.html { # show.html.erb
        @flyer_info = FlyerInfo.find(params[:id])
      }
      format.json {
        render json: getflyer(params[:id])
      }
    end

  end

  # GET /flyer_infos/new
  # GET /flyer_infos/new.json
  def new
    respond_to do |format|
      format.html {  # new.html.erb
        @flyer_info = FlyerInfo.new
      }
    end
  end

  # GET /flyer_infos/1/edit
  def edit
    @flyer_info = FlyerInfo.find(params[:id])
  end

  # POST /flyer_infos
  # POST /flyer_infos.json
  def create
    respond_to do |format|
      format.html {
        @flyer_info = FlyerInfo.new(params[:flyer_info])
        if @flyer_info.save
          GameInfoHelper.updateTime
          redirect_to @flyer_info, notice: 'Flyer info was successfully created.'
        else
          render action: "new"
        end
      }
      format.json {
        if ApplicationHelper.validate_key(request.headers["Validation-Key"])
          @flyer_info = FlyerInfo.new(params[:flyer_info])
          if @flyer_info.save
            GameInfoHelper.updateTime
            render json: @flyer_info.as_json(:only => [:id])
          else
            render json: @flyer_info.errors, status: :unprocessable_entity
          end
        else
          create_error(:forbidden, :post, params[:flyer_info], "Data incorrect")
        end
      }
    end
  end

  # PUT /flyer_infos/1
  # PUT /flyer_infos/1.json
  def update
    # JSON is not allowed to modify flyer_infos. Must be done through the website.
    respond_to do |format|
      format.html {
        @flyer_info = FlyerInfo.find(params[:id])
        if @flyer_info.update_attributes(params[:flyer_info])
          GameInfoHelper.updateTime
          redirect_to @flyer_info, notice: 'Flyer info was successfully updated.'
        else
          render action: "edit"
        end
      }
      format.json {
        create_error(:forbidden, :put, params[:flyer_info], "Data incorrect")
      }
    end
  end

  # DELETE /flyer_infos/1
  # DELETE /flyer_infos/1.json
  def destroy
    # JSON is not allowed to destroy item_infos. Must be done through the website.
    respond_to do |format|
      format.html {
        @flyer_info = FlyerInfo.find(params[:id])
        @flyer_info.destroy
        GameInfoHelper.updateTime
        redirect_to flyer_infos_url
      }
      format.json {
        create_error(:forbidden, :delete, params[:flyer_info], "Data incorrect")
      }
    end
  end
end

app/helpers/flyer_infos_helper.rb
module FlyerInfosHelper

  def FlyerInfosHelper.getflyerloc(flyer_info, language)
    flyer_loc_array = flyer_info.flyer_locs.where("locale = ?", language).select("locale, localized_name, localized_desc")
    if flyer_loc_array.empty?
      # There is no corresponding item_loc for this item_info. Fake one for now to prevent failure.
      flyer_loc = ItemLoc.new
      flyer_loc_array = [ flyer_loc ]
    end
    flyer_loc_array
  end

end

app/views/flyer_infos/_form.html.erb
<%= form_for(@flyer_info) do |f| %>
  <% if @flyer_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flyer_info.errors.count, "error") %> prohibited this flyer_info from being saved:</h2>

      <ul>
      <% @flyer_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :tier %><br />
    <%= f.number_field :tier %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :load_time %><br />
    <%= f.number_field :load_time %>
  </div>
  <div class="field">
    <%= f.label :speed %><br />
    <%= f.number_field :speed %>
  </div>
  <div class="field">
    <%= f.label :stormresist %><br />
    <%= f.number_field :stormresist %>
  </div>
  <div class="field">
    <%= f.label :multiplier %><br />
    <%= f.number_field :multiplier %>
  </div>
  <div class="field">
    <%= f.label :topimg %><br />
    <%= f.text_field :topimg %>
  </div>
  <div class="field">
    <%= f.label :sideimg %><br />
    <%= f.text_field :sideimg %>
  </div>
  <div class="field">
    <%= f.label :disabled %><br />
    <%= f.check_box :disabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flyer_infos/edit.html.erb
<h1>Editing flyer_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @flyer_info %> |
<%= link_to 'Back', flyer_infos_path %>

app/views/flyer_infos/index.html.erb
<h1>Listing flyer_infos</h1>

<table>
  <tr>
    <th>Price</th>
    <th>Tier</th>
    <th>Capacity</th>
    <th>Load Time</th>
    <th>Speed</th>
    <th>Stormresist</th>
    <th>Multiplier</th>
    <th>Top Image</th>
    <th>Side Image</th>
    <th>Disabled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flyer_infos.each do |flyer_info| %>
  <tr>
    <td><%= flyer_info.price %></td>
    <td><%= flyer_info.tier %></td>
    <td><%= flyer_info.capacity %></td>
    <td><%= flyer_info.load_time %></td>
    <td><%= flyer_info.speed %></td>
    <td><%= flyer_info.stormresist %></td>
    <td><%= flyer_info.multiplier %></td>
    <td><%= flyer_info.topimg %></td>
    <td><%= flyer_info.sideimg %></td>
    <td><%= flyer_info.disabled %></td>
    <td><%= link_to 'Show', flyer_info %></td>
    <td><%= link_to 'Edit', edit_flyer_info_path(flyer_info) %></td>
    <td><%= link_to 'Destroy', flyer_info, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flyer info', new_flyer_info_path %>

app/views/flyer_infos/new.html.erb
<h1>New flyer_info</h1>

<%= render 'form' %>

<%= link_to 'Back', flyer_infos_path %>

app/views/flyer_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Price:</b>
  <%= @flyer_info.price %>
</p>

<p>
  <b>Tier:</b>
  <%= @flyer_info.tier %>
</p>

<p>
  <b>Capacity:</b>
  <%= @flyer_info.capacity %>
</p>

<p>
  <b>Load time:</b>
  <%= @flyer_info.load_time %>
</p>

<p>
  <b>Speed:</b>
  <%= @flyer_info.speed %>
</p>

<p>
  <b>Stormresist:</b>
  <%= @flyer_info.stormresist %>
</p>

<p>
  <b>Multiplier:</b>
  <%= @flyer_info.multiplier %>
</p>

<p>
  <b>Top Image:</b>
  <%= @flyer_info.topimg %>
</p>

<p>
  <b>Side Imgage:</b>
  <%= @flyer_info.sideimg %>
</p>

<p>
  <b>Disabled:</b>
  <%= @flyer_info.disabled %>
</p>

<h2>Localized information</h2>
<% @flyer_info.flyer_locs.each do |flyer_loc| %>
    <p>
      <b>Locale:</b>
      <%= flyer_loc.locale %>
    </p>

    <p>
      <b>Localized name:</b>
      <%= flyer_loc.localized_name %>
    </p>

    <p>
      <b>Localized description:</b>
      <%= flyer_loc.localized_desc %>
    </p>
<% end %>

<h2>Add localized information:</h2>
<%= form_for([@flyer_info, @flyer_info.flyer_locs.build]) do |f| %>
    <div class="field">
      <%= f.label :locale %><br />
      <%= f.text_field :locale %>
    </div>
    <div class="field">
      <%= f.label :localized_name %><br />
      <%= f.text_field :localized_name %>
    </div>
    <div class="field">
      <%= f.label :localized_desc %><br />
      <%= f.text_field :localized_desc %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Edit', edit_flyer_info_path(@flyer_info) %> |
<%= link_to 'Back', flyer_infos_path %>